[build]
  functions = "functions/"
  publish = "dist/"
  command = "npm start"

[template.environment]
  API_URL = "https://maps.googleapis.com/maps/api/geocode/json"
  API_TOKEN = "AIzaSyB2Z4Lk0QfR6QngDRAQM6k0mzP7NJAu1vs"

[[redirects]]
from="/api"
to=".netlify/functions/getapi"
status=200
