[build]
  functions = "functions/"
  publish = "dist/"
  command = "npm run build"

[template.environment]
  API_URL = "https://maps.googleapis.com/maps/api/geocode/json"
  API_TOKEN = ""

[[redirects]]
from="/api"
to=".netlify/functions/getapi"
status=200
